version: '3'

volumes:
  vol-db:

services:

  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - ./vol-db:/data/postgres
    ports:
      - "5432:5432"
    expose:
      - 3306
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: ugur
      POSTGRES_DB: db
      PGDATA: /data/postgres


  afs:
    image: ucekmez/afs
    container_name: afs
    volumes:
      - $PWD:/workspace/data
    ports:
      - 7778:8888
    links:
      - db
    depends_on:
      - db
